default:
  tags:
    - runner-rcs-gsi 

main-ci:
  only: 
    - merge_requests
  image: docker/compose:latest
  script:
    - cp testsecret.env secret.env
    - docker-compose down
    - docker-compose up -d --build rmq 
    - docker-compose up --build gsi 

linter:
  only:
    - merge_requests
  image: python:3.8.12-slim-buster
  script: 
    - python -m pip install --upgrade pip
    - pip install flake8
    - flake8


include:
  - project: 'nrt-crew/common/templates'
    ref: develop
    file: '/gitlab-ci/versioning.gitlab-ci.yml'
  #- project: 'nrt-crew/common/templates'
  #  ref: develop
  #  file: '/gitlab-ci/helm-jobs.gitlab-ci.yml'
  - project: 'nrt-crew/common/templates'
    ref: develop
    file: '/gitlab-ci/kaniko-jobs.gitlab-ci.yml'
