default:
  tags:
    - runner-rcs-gsi 

main-ci:
  only: 
    - pushes
    - merge_requests
  image: docker/compose:latest
  script:
    - cp testsecret.env secret.env
    - docker-compose up -d rmq
    - docker-compose up gsi

linter:
  only:
    - pushes
  image: python:3.8.12-slim-buster
  script: 
    - python -m pip install --upgrade pip
    - pip install flake8
    - flake8


deploy:
  only: 
    - push
    - tags
  image: docker:18.09-dind
  script:
    - export 
    - echo ${CI_COMMIT_TAG}
    - docker login -u ${CI_DEPLOY_USER} -p ${CI_DEPLOY_PASSWORD} ${CI_REGISTRY}
    

    - docker build -t ${CI_REGISTRY_IMAGE}/gsi:latest -t ${CI_REGISTRY_IMAGE}:tag -f ./docker/gsi/Dockerfile . 
    - docker build -t ${CI_REGISTRY_IMAGE}/rmq:latest -t ${CI_REGISTRY_IMAGE}:tag -f ./docker/rmq/Dockerfile . 


    - docker push {CI_REGISTRY_IMAGE}/gsi:latest
    - docker push {CI_REGISTRY_IMAGE}/gsi:tag
      
      
    - docker push {CI_REGISTRY_IMAGE}/rmq:latest
    - docker push {CI_REGISTRY_IMAGE}/rmq:tag
    



