default:
  tags:
    - runner-rcs-gsi 

main-ci:
  only: 
    - pushes

  image: docker:latest

  services:
    - docker:dind

  variables:
    # can this be set in the runner?
    DOCKER_DRIVER: overlay2

  stages:
  - test

  before_script:
    - apk add --no-cache py-pip
    - pip install docker-compose
    - docker info

  test:
    stage: test
    script:
      - cp testsecret.env secret.env
      - docker-compose up -d rmq
      - docker-compose up gsi

linter:
  only:
    - pushes
  image: python:3.8.12-slim-buster
  script: 
    - python -m pip install --upgrade pip
    - pip install flake8
    - flake8


deploy:
  only: 
    - tags
  image: docker:18.09-dind
  script:
    - echo ${CI_COMMIT_TAG}
    - docker login -u ${CI_DEPLOY_USER} -p ${CI_DEPLOY_PASSWORD} ${CI_REGISTRY}


