default:
  tags:
    # in order to build and push the images
    # always in the same runner, 
    # just put a unique tag
    - runner-rcs-gsi 


image: centos:7

test:
    script:
        - echo "This test should fail" && exit 1
