workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == 'push'
      when: always

stages:
  - .pre
  - prepare
  - build
  - test
  - deploy
  - .post

linter:
  only:
    - merge_requests
  image: python:3.8.12-slim-buster
  script: 
    - python -m pip install --upgrade pip
    - pip install flake8
    - flake8


include:
  - project: 'nrt-crew/common/templates'
    ref: develop
    file: '/gitlab-ci/versioning.gitlab-ci.yml'
  - local: '.workflows/build-wheel.yaml'
  