default:
  tags:
    - runner-rcs-gsi 

main-ci:
  only: 
    - pushes
   allow_failure:
     exit_codes:
      - 5
  image: docker/compose:latest
  script:
    - cp testsecret.env secret.env
    - docker-compose up -d rmq
    - docker-compose up gsi


delpoy:
  only: 
    - tags
  script:
    - echo "Release"

