version: '3.8'

services:
    gsi:
        environment:
          - PYTHONDONTWRITEBYTECODE=1
        env_file:
          - environment.env
          - testsecrets.env
        build:
            context: .
            dockerfile: ./docker/gsi/Dockerfile
        image: gsi
        container_name: gsi
        entrypoint: pytest -p no:cacheprovider
        volumes:
            - ./rcsmq:/opt/code
        depends_on:
            - rmq

    rmq:
        env_file:
          - environment.env
          - testsecrets.env
        build:
            context: .
            dockerfile: ./docker/rmq/Dockerfile
        image: rmq
        container_name: rmq
        ports:
            - "5672:5672"
            - "15672:15672"
