version: '3.8'

services:
    gsi:
        environment:
          - PYTHONDONTWRITEBYTECODE=1
        build:
            context: .
            dockerfile: ./docker/gsi/Dockerfile
        image: gsi
        container_name: gsi
        command: tail -f /dev/null
        depends_on:
            - rmq

    rmq:
        env_file:
          - environment.env
          - secrets.env
        build:
            context: .
            dockerfile: ./docker/rmq/Dockerfile
        image: rmq
        container_name: rmq
        ports:
            - "5672:5672"
            - "15672:15672"
