FROM python:3.10.8-alpine3.15 AS compile-image

RUN mkdir -p /opt/code
WORKDIR /opt/code

# Install dependencies
RUN apk add python3-dev build-base gcc linux-headers postgresql-dev libffi-dev

# Create a virtual environment for all the Python dependencies
RUN python3 -m venv /opt/venv
# Make sure we use the virtualenv:
ENV PATH="/opt/venv/bin:$PATH"
RUN pip3 install --upgrade pip

# Install other dependencies
COPY mqclient/requirements.txt /opt/
RUN pip3 install -r /opt/requirements.txt


########
# This image is the runtime, will copy the dependencies from the other
########
FROM python:3.10.8-alpine3.15 AS runtime-image

RUN mkdir -p /opt/


# Create a user to run the service
RUN addgroup -S rcs
RUN adduser -H -D -S rcs
USER rcs

# Copy the venv with compile dependencies from the compile-image
COPY --chown=rcs:rcs --from=compile-image /opt/venv /opt/venv

# Be sure to activate the venv
ENV PATH="/opt/venv/bin:$PATH"

# Make sure we can import modules in/opt/code
ENV PYTHONPATH='/opt/code:$PYTHONPATH'

# Copy the code
COPY --chown=rcs:rcs mqclient/ /opt/code/

# Set working directory
WORKDIR /opt/code
