name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  notifyStart:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: wp-4-github
        SLACK_COLOR: '#3278BD'
        SLACK_ICON: https://github.com/newrobotictelescope.png?size=48
        SLACK_MESSAGE: 'Starting CI/CD Tests :rocket:'
        SLACK_TITLE: Action
        SLACK_USERNAME: nrtbot
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Bring up the gsi and rmq
      run: docker-compose up -d
    - name: Run tests on the gsi
      run: docker run gsi pytest
    - name: Bring down the system
      run: docker-compose down
    - name: Build the Docker image
      run: docker build . --file docker/gsi/Dockerfile --tag gsi:$(date +%s)

  reportResult:
    - uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }} # required
      if: always() # Pick up events even if the job fails or is canceled.
