name: Publish Docker image
on:
  release:
    types: [published]

jobs:
  path-context:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Notify of Start on Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: wp-4-github
          SLACK_COLOR: '#3278BD'
          SLACK_ICON: https://github.com/newrobotictelescope.png?size=48
          SLACK_TITLE: Message
          SLACK_MESSAGE: 'New Release of 4mnrt/gsi image to DockerHub! :rocket:'
          SLACK_FOOTER: ''
          SLACK_USERNAME: nrtbot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/gsi/Dockerfile
          push: true
          tags: |
            4mnrt/gsi:latest
            4mnrt/gsi:${{ steps.get_version.outputs.VERSION }}

      - name: Report Result to Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }} # required
        if: always() # Pick up events even if the job fails or is canceled.
